POST http://localhost:3000/auth/register
Content-Type: application/json

{
	"email": "louieaniez@gmail.com",
	"password": "test123!@#"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "louieaniez@gmail.com",
	"password": "test123!@#"
}

###

GET http://localhost:3000/quiz/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MDgxNzE1LCJleHAiOjE2NTYwODIzMTV9.fJkD_xj__Ex26rBprS-6k_BsyShY-8m4i2XZfHx_k5c

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MDU1NDQ1fQ._OB2eCs6b4qE6qNjzh7TgkmB7LyEsjTy_w9FVJ6INF4"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MDU1NDQ1fQ._OB2eCs6b4qE6qNjzh7TgkmB7LyEsjTy_w9FVJ6INF4"
}

###

POST http://localhost:3000/quiz/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MDcxNzM2LCJleHAiOjE2NTYwNzIzMzZ9.tWZ5SpjEhtUDnVRwabhbXhNsIuVO1GjNNrbOUxFjtqA

{
	"title": "Test quiz",
	"status": "saved",
	"questions": [
		{
			"type": "single",
			"question": "What is your name?",
			"choices": [
				{
					"label": "James Reid",
					"checkanswer": false
				},
				{
					"label": "Dexter Louie Aniez",
					"checkanswer": true
				}
			]
		},
		{
			"type": "multiple",
			"question": "What is my name?",
			"choices": [
				{
					"label": "Dexter Louie Aniez",
					"checkanswer": false
				},
				{
					"label": "James Reid",
					"checkanswer": true
				}
			]
		}
	]
}