POST http://localhost:3000/auth/register
Content-Type: application/json

{
	"email": "louieaniez@gmail.com",
	"password": "test123!@#"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
	"email": "louieaniez@gmail.com",
	"password": "test123!@#"
}

###

GET http://localhost:3000/quiz/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MTIxNDc4LCJleHAiOjE2NTYxMjIwNzh9.lev9O6KWkafnJoaoBrlbau1vA4cktXF-oP-hAG2v4H0

###

POST http://localhost:3000/auth/token
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MTExOTAwfQ.ZM1ycyAU-yrPzJjKZIAe_vP8fpB1yvhgVVNbbP-q1uw"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MDU1NDQ1fQ._OB2eCs6b4qE6qNjzh7TgkmB7LyEsjTy_w9FVJ6INF4"
}

###

POST http://localhost:3000/quiz/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MTExOTAwLCJleHAiOjE2NTYxMTI1MDB9.Tvt2I2AjP5WudU4VZGNnlosS6DLzZU46fEavbXkttWE

{
	"title": "Philippines",
	"status": "saved",
	"questions": [
		{
			"type": "single",
			"question": "Who is the current president of the Philippines?",
			"choices": [
				{
					"label": "BongBong Marcos Jr.",
					"checkanswer": true
				},
				{
					"label": "Dexter Louie Aniez",
					"checkanswer": true
				}
			]
		},
		{
			"type": "multiple",
			"question": "Nganong gwapo kaayo si Dexter Louie Aniez?",
			"choices": [
				{
					"label": "Secret",
					"checkanswer": false
				},
				{
					"label": "Basta kay secret",
					"checkanswer": true
				}
			]
		}
	]
}

###

GET http://localhost:3000/visitor/view/cnct0eh7ps00

###

POST http://localhost:3000/quiz/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvdWllYW5pZXpAZ21haWwuY29tIiwiaWF0IjoxNjU2MTE5NjY4LCJleHAiOjE2NTYxMjAyNjh9.kxBwaDWkipaNt7x8faBOjUKtybG-EBoaYcEHJVglR1k

{
	"quiz": {
		"id": 4,
		"title": "Pagwapohay updated",
		"status": "published"
	},
	"questions": [
		{
			"id": 6,
			"type": "multiple",
			"question": "Kinsay Maot updated"
		}
	],
	"choices": [
		{
			"id": 8,
			"label": "Bouyancy force updated",
			"checkanswer": true
		}
	]
}

###

POST http://localhost:3000/visitor/answer
Content-Type: application/json

{
	"userid": "gsef",
	"quizid": 2,
	"questionsanswered": [
		{
			"id": 3,
			"answers": [5]
		},
		{
			"id": 4,
			"answers": [8]
		}
	]
}
